### ISSUE TITLE
Unrecognized firmware DS1823xs+?

### ISSUE THREAD

**Issue by 70m7E** [007revad/Synology_HDD_db#87] opened 2023-06-11 04:54 UTC
I am probably doing something wrong, since it seems to work for everyone else: I still get the 'unrecognized firmware' on all my drives. Although sometimes that message is gone and everything seems fine; I cant repeat it though.  

Here is the output of my script when run manually, the error message seems new:

![Screenshot 2023-06-11 at 12 45 35 PM](https://github.com/007revad/Synology_HDD_db/assets/84424468/b97c0eea-e890-46e1-a8ba-f1ee6e29928e)

Here is the config in task scheduler, with options -nr: 

![Screenshot 2023-06-11 at 12 49 30 PM](https://github.com/007revad/Synology_HDD_db/assets/84424468/b677f397-593b-41db-9de7-246630917f11)

Side-note: I also added an old M2D20 to my DS1823xs+, with one M2 drive. The script 1.0.6 indeed finds it and displays the correct M2 disk. Not sure if you can solve this, but would be nice if the NAS would be able to access it. So far it only displays the drives 1-8, 2xM2 build in slots, but not the M2D20 drive under storage manager:

![Screenshot 2023-06-11 at 12 49 13 PM](https://github.com/007revad/Synology_HDD_db/assets/84424468/97c3178c-c27d-45f4-9748-5b8b5ce168f2)

Issue: 
![Screenshot 2023-06-11 at 1 06 01 PM](https://github.com/007revad/Synology_HDD_db/assets/84424468/0ddc829a-5002-4e2b-8277-ffb11659d987)

**Comment by 007revad** [comment] 2023-06-11 10:21
I'm surprised more people aren't complaining about these issues. You're only the 3rd person who's mentioned them since DSM 7.2 was officially released. Because of the reports by the other 2 people I've been working on fixing these issues.

Things I've already fixed **(but I haven't released the updated version yet)**.
1. I've changed the script to avoid the error that is on line 4 of your first screenshot... but I need to investigate why some people with M2 drives don't have /run/synostorage/disks/nvme0n1/m2_pool_support 
2. The firmware version being only 4 characters for HDD/SSD SATA (and SAS?) drives - which is the cause for "Unsupported firmware version" message in storage manager. I've changed how the script gets HDD/SSD firmware version.
3. Installed memory being returned as GB instead of MB. I've changed the script to work with GB or MB.

Do you want to try [Synology_HDD_db v2.3.49-RC](https://github.com/007revad/Synology_HDD_db/releases/tag/v2.3.49-RC)

Does your "Samsung SSD 960 PRO 2TB" show in storage manager without the "Unsupported firmware version" message? Or is it the NVMe drive that is in the M2D20 that does not show at all in storage manager?

FYI If you previously ran either script with an older version of DSM (DSM 6 or 7.1.1 etc) do **_NOT_** run the syno_hdd_bd.sh with the --restore option. It will restore the old DSM version's backup of synoinfo.conf and you'll lose access to storage manager and few tabs in control panel. I'm working on a fix for this issue.

**Comment by 007revad** [comment] 2023-06-13 06:17
So the 2 M.2 drives in the internal M.2 slots of the DS1823xs+ still show "Unrecognized firmware version"?

I only discovered yesterday that the M2D20 only works with certain models, but not the DS1823xs+ or my DS1821+. And I have no idea how Synology pick which models to make it work with. To me, if it has a PCIe slot any M.2 or network card should work.
https://www.synology.com/en-global/products/M2D20#specs

The M2D20 card also does not work in my DS1821+ but it does work in a DS1819+ !?!?!  I might compare those 2 models' DSM files to see if I can work out how to enable M2D20 support in officially unsupported models.

My Synology_M2_volume script should be able to create a storage pool on the M.2 drives in the M2D20. https://github.com/007revad/Synology_M2_volume You'd then go into storage manager and do an online assemble then create your volume. After that you could then setup the M2 drives in the internal M.2 slots of the DS1823xs+ as a cache from within storage manager.

**Comment by 007revad** [comment] 2023-06-16 07:39
> Note, to enable those M2 drives plugged into the internal M2 slots (not the M2D20) as storage volume I had to use the 
> enable_M2 script originally when I first set it up. I was surprised to read in your other thread here that everything is now 
> handled by the hdd_db script and the enable_M2 is not needed anymore.

The hdd_db script on it's works for Synology NAS models that officially support M2 volumes. The enable_M2 script also works on those models, but seems to also work on some models that don't officially support M2 volumes.

> M2D20: I ran the Synology_M2_volume as dry run; it seems I could create a pool with the M2D20 drive, but a) is that safe, since the drive is not even displayed under HDD in storage manager (?), 

I would try it just to see if they can then be seen in Storage Manager. 

> and b) it wouldn't solve that I want to use the drive as read-cache, right now storage manager says "no drive available", when I try to add a read-cache SSD (?)

If moving the 2 crucial drives to the M2D20 makes them appear as volume (because they already have a volume setup), you could then use the Samsung drive in the DS1823xs+ as cache.

Officially the DS1823xs+ does not support M2D20, M2D18 or E10M20-T1.

I'm interested in seeing if I can make the M2D20, M2D18 and E10M20-T1 become supported on NAS models that don't support them. Unfortunately I don't have an M2D20, M2D18 or E10M20-T1 to test with.

According to Synology my DS1821+ does not support the M2D20, M2D18 or E10M20-T1, yet DSM for the DS1821+ includes disk compatibility .db files for E10M20-T1, M2D20, M2D18 and M2D17.

**Comment by 007revad** [comment] 2023-06-16 08:33
What do the following 2 commands return?

`ls /run/synostorage/disks `

`ls /sys/block | grep nvme`

**Comment by 007revad** [comment] 2023-06-16 22:25
I think I may have found how to enable your M2D20 card. Can you try the following command:

`sudo set_section_key_value /usr/syno/etc.defaults/adapter_cards.conf M2D20_sup_nvme DS1832xs+ yes`

then reboot.

**Comment by 007revad** [comment] 2023-06-17 04:33
Excellent. I was hoping you'd say it worked because while I was waiting for your reply I went ahead and wrote the code to add it the script.

Did you need to reboot to the see M2D20 in storage manager?

Regarding the Crucial NVMe drives, I'm wondering if it needs to be "Crucial CT4000P3PSSD8" instead of "CT4000P3PSSD8".

Can you save the DS1823xs+__host_v7.db file, zip it and attach the zip file to your reply.
`sudo -i cp /var/lib/disk-compatibility/ds1823xs+_host_v7.db ~/ds1823xs+_host_v7.db`

**Comment by 007revad** [comment] 2023-06-17 07:58
Can you replace /var/lib/disk-compatibility/ds1823xs+_host_v7.db with the one in the attached zip file.
[edited_ds1823xs+_host_v7.zip](https://github.com/007revad/Synology_HDD_db/files/11778275/edited_ds1823xs%2B_host_v7.zip)

Then either reboot or run the following command:
`sudo /usr/syno/sbin/synostgdisk --check-all-disks-compatibility`

**Comment by 007revad** [comment] 2023-06-17 09:44
You don't get any output from `sudo /usr/syno/sbin/synostgdisk --check-all-disks-compatibility`. The only way to check if synostgdisk did anything is by checking it's return status was 0 with `echo $?`

Do the Crucial NVMe drives still show unsupported firmware?

**Comment by 007revad** [comment] 2023-06-20 10:00
Try running it with the -f option.

**Comment by 007revad** [comment] 2023-06-22 01:58
You could try running the [Synology_enable_M2_volume](https://github.com/007revad/Synology_enable_M2_volume) script... but I'd like to find out why syno_hdd_db is not fully working for you.

What does the following command return:
`sudo synodisk --enum -t cache`

Did you ever try one of the Crucial NVMe drives in the M2D20? Or the Samsung NVMe drive in the DS1821xs+? I'm curious if the Crucial still has the warning when it is in the M2D20, and if the Samsung still has no warning when in one of the NAS' M.2 slots.

**Comment by 007revad** [comment] 2023-06-22 04:51
Yep, that "Tempeture" stands out.

I forgot that you've already run synology_enable_m2_volume 2 weeks ago.

> ************ Disk Info ***************
> Disk id: 1
> Slot id: 1
> Disk path: /dev/nvme0n1
> Disk model: Samsung SSD 960 PRO 2TB
> ************ Disk Info ***************
> Disk id: 1
> Disk path: /dev/nvme1n1
> Disk model: CT4000P3PSSD8
> ************ Disk Info ***************
> Disk id: 2
> Disk path: /dev/nvme2n1
> Disk model: CT4000P3PSSD8

It's interesting that DSM assigned /nvme0n1 to the Samsung in the M2D20, and then /dev/nvme1n1 and /dev/nvme2n1 to the 2 NVMe drives in the NAS' internal M.2 slots. It's also interesting that there's 2 "Disk id: 1".

My script, synodisk and Storage Manager all show the same CT4000P3PSSD8 model number for the Crucial drives.  My script and Storage Manager both show the same P9CR40A firmware version for the Crucial drives. 

Do these return the P9CR40A firmware version?
```
sudo synonvme --sn-fr-get /dev/nvme1
sudo synonvme --sn-fr-get /dev/nvme2
```

Do these return the CT4000P3PSSD8 model number?
```
sudo synonvme --model-get /dev/nvme1
sudo synonvme --model-get /dev/nvme2
```

**Comment by 007revad** [comment] 2023-06-29 06:55
Sorry, I took a few days to think about your issue and forgot reply earlier.

I've got 2 different ds1823xs+_host_v7.db files for you to try.
[ds1823xs+_host_v7_new.zip](https://github.com/007revad/Synology_HDD_db/files/11902526/ds1823xs%2B_host_v7_new.zip)

**Comment by 007revad** [comment] 2023-07-08 11:41
There have only been a few people who mentioned Crucial NVMe drives: Mostly people reporting that the script worked for their Synology model and with a Crucial NVMe. None of them had '23 series xs+ model.

But there was 1 person on reddit who had an Crucial NVMe drive die after less than a week. So they got a replacement and it too died in less than a week. They then got a Samsung NVMe and everything was fine.

I've searched through the 112 different Synology models' DSM 7.2 host .db files for any crucial drives: One of them had 1 instance of "Crucial_CTxxxxx" but others as "CTxxxxx" and the other 58 models that contained an entry for a Crucial drive all had "CTxxxxx". The only xs+ models who's DSM 7.2 host .db files contained entries for Crucial drives were '17 and '19 series. I was hoping to find something different in from the xs+ models.

I suspect something has changed in DSM 7.2 for recent xs+ models. There was 1 person on reddit with an xs+ model who had to run the Synology_HDD_db script 3 times before all of their drives stopped showing the firmware warning. I don't know if they rebooted after each time they ran the script, or if they just ran it 3 times and rebooted.

The Samsung SSD 960 PRO 2TB is still in the M2D20 card?
And the 2x Crucial CT4000P3PSSD8 drives are still in the internal M.2 slots?

Can you run the Synology_enable_M2_volume script with the --restore option then reboot - just in case it's somehow causing the NVMe drives in the internal M.2 slots to still show the firmware warning.

**Closed** 2023-07-09 10:22 UTC

**Comment by 007revad** [comment] 2023-09-23 20:42
@70m7E 
Can you do me a favor and tell me what these commands return?

`cat /proc/sys/kernel/syno_hw_version`

`cat /etc.defaults/VERSION`

`ll /sys/firmware/devicetree`

`cat /sys/firmware/devicetree/base/power_limit && echo`

**Comment by golovan** [comment] 2024-03-02 01:17
The same drive model and the same problem for me. Tried to -- restore but no luck. This script is applied on shutdown and HDD_db one on the boot. Any further ideas, @007revad?

**Comment by 007revad** [comment] 2024-03-02 01:26
> This script is applied on shutdown and HDD_db one on the boot.

Which script do you have scheduled to run on shutdown?

**Comment by golovan** [comment] 2024-03-02 01:37
Sorry, need to sleep a bit :) Synology_enable_M2_volume is on shutdown.

**Comment by golovan** [comment] 2024-03-02 06:42
Solved. Disabling syno_enable_m2_volume from run and running syno_enable_m2_volume.sh --restore helped! Do I understand correctly there is no need in syno_enable_m2_volume anymore and Synology_HDD_db enables m2 volumes as well? @007revad

**Comment by 007revad** [comment] 2024-03-02 07:17
@golovan 

> Solved. Disabling syno_enable_m2_volume from run and running syno_enable_m2_volume.sh --restore helped! 

That was what I was going to suggest.

> Do I understand correctly there is no need in syno_enable_m2_volume anymore and Synology_HDD_db enables m2 volumes as well?

Correct. For '20 series and later models with DSM 7.2.1 you only need Synology_HDD_db.

**Comment by reinhead** [comment] 2024-12-03 10:43
I have a DS923+ and recently bought 2 x M2 Crucial P3 Plus drives. Found this thread because I also had the unrecognized firmware issue for the M2 Crucial drives. Can confirm that disabling syno_enable_m2_volume, restoring and only running Synology_HDD_db solved everything here as well. Thanks!
