### ISSUE TITLE
Not working for rs3621xs+ on DSM 6.2.4-25556

### ISSUE THREAD

**Issue by nightmadeoflight** [007revad/Synology_HDD_db#11] opened 2023-03-17 13:25 UTC
Drives added (and now showing as "already existing"):
WD4002FFWX-68TZ4N0 already exists in rs3621xs+_host.db
WD4002FFWX-68TZ4N0 already exists in rs3621xs+_host.db.new
WD40EFRX-68WT0N0 already exists in rs3621xs+_host.db
WD40EFRX-68WT0N0 already exists in rs3621xs+_host.db.new

Before the reboot., I get notifications on the Synology web interface to say they are unverified (each time you run the script).
After a reboot,  they are still showing unverified.

**Comment by 007revad** [comment] 2023-03-18 03:36
Can you please attach get a copy of your rs3621xs+_host.db file:

`sudo cp /var.defaults/lib/disk-compatibility/rs3621xs+_host.db $HOME/rs3621xs+_host.db.txt`

Then reply here and attach the rs3621xs+_host.db.txt file.

If you don't have the home folder service enabled change $HOME in the command above to a path you have access to.

**Comment by 007revad** [comment] 2023-03-22 22:38
OP not responding

**Comment by nightmadeoflight** [comment] 2023-03-23 14:48
I upgraded DSM to the latest version 7 (from 6), ran the script and it
worked. :)

**Comment by Greg-ATG** [comment] 2023-04-13 16:43
The issue here may be that some NAS models running DSM6 still reference the "X_v7.db" files.  Actually, now that I think about it, our NAS (RS2421RP+) shipped with DSM7, but we completed a downgrade procedure to DSM6.  Perhaps this is why it's referencing the v7 databases.

This would explain why @nightmadeoflight upgrading their NAS to DSM7 fixed the issue, since then this script would have started fixing the v7 database files.

Perhaps it's safest to modify the v7 database files (if present) regardless of the DSM version?

**Comment by 007revad** [comment] 2023-04-17 08:17
@Greg-ATG 

I've only seen X.db files in DSM 6 and X_v7.db files in DSM 7... but there could be situations where someone's Synology has both. I know when you upgrade from DSM 6 to DSM 7 it appends _v7 to all the .db file names.

Since you have downgraded from DSM 7 to DSM 6 I'm curious if your RS2421RP+ now has both X.db and X_v7.db files? Can you run the following command to see what it returns:

`ls /var/lib/disk-compatibility/*.db`

**Comment by Greg-ATG** [comment] 2023-04-17 20:22
Yes, the disk-compatibility directory contains both X.db and X_v7.db files for us.  This must be related to the DSM6 downgrade.

**Comment by 007revad** [comment] 2023-04-21 08:33
@Greg-ATG 

I'm working on changing the script to ignore the DSM version and update all the host db files it finds. This will avoid the issue you had, and cater for any changes by new DSM versions in future. As it requires quite a few changes it'll take a couple of days to finish and test.

I'd like to get to you to test it when I'm finished.

**Comment by Greg-ATG** [comment] 2023-04-21 17:42
Sounds good, no rush.  I'll help out however I can.

**Comment by 007revad** [comment] 2023-04-23 09:41
@Greg-ATG 

I've got a new pre-release version that should solve the issue of DSM 6 using X_v7.db files after downgrading from DSM 7 to DSM 6. https://github.com/007revad/Synology_HDD_db/releases/tag/v2.2.40

It also has a new --restore option to undo all changes previously made by the script so you can test v2.2.40 with clean db files and synoinfo.conf file.

Can you please: 
1. First run v2.2.40 with the --restore option: `sudo syno_hdd_db --restore`
2. Then check that your drives show as unsupported.
3. Then run it again with your preferred options and check that your drives do NOT show as unsupported.

It works perfectly in my test environment where I simulate having two expansion units and an M.2 card. But as I don't actually have an expansion unit or M.2 card I wouldn't be surprised if there's a bug that I didn't find.

**Comment by 007revad** [comment] 2023-04-23 22:58
Sorry, that pre-release version was mistakenly the same v2.1.38 !

Try the new https://github.com/007revad/Synology_HDD_db/releases/tag/v2.2.42

**Comment by Greg-ATG** [comment] 2023-04-24 15:29
I ran the script with restore mode (nice feature!) with the following output:

![image](https://user-images.githubusercontent.com/130684415/234019620-31d12071-8708-46cc-afc8-10df8491bd1b.png)

However, the NAS reported NO unverified drives after a reboot.  Upon closer inspection, I found the following:

- rs2421rp+_host.db: Clean (no references to custom disk model)
- rs2421rp+_host.db.new: Redundant references to custom disk model (see highlighting in screenshot below)
- rs2421rp+_host_v7:db: Single reference to custom disk model
- rs2421rp+_host_v7.db.new: Clean (in hindsight, this was likely not the case as I was only looking at the beginning of the file, not the end, where it seems this script seems to add it for v7 files)

I'm not sure if these inconsistencies are bugs with the restore mode or (more likely) a result of the tinkering I had previously done with these files.

![image](https://user-images.githubusercontent.com/130684415/234021376-6623fd11-8660-400f-a6da-5c038d81ff49.png)

I manually cleaned up all of these files and rebooted the NAS, which resulted in the expected unverified disks warning.  I then ran the script with my preferred parameters (-showedits -noupdate -m2) and I'm happy to report that there was no unverified disk warning after rebooting and all the DB files look correct (it was at this point that I realized that this script adds the modifications to v7 files _at the end_, hence my note up above about v7.db.new, and I manually cleaned up the v7.db.new.bak file).

In the interest of science, I ran the script in restore mode again and can confirm that everything was restored correctly.  I than ran and rebooted twice using my preferred parameters.  After the first execution, everything looked good, but after the second one, it appears duplicate entries were added to the regular (v6) DB files:

![image](https://user-images.githubusercontent.com/130684415/234042042-11d8a110-4b5e-4704-9ccf-fa5737ae54b8.png)

This is confirmed by the script log (for the second execution), which shows that the v6 files were "re-patched" while the v7 files were correctly detected as "already exists":

![image](https://user-images.githubusercontent.com/130684415/234043541-26741a02-8012-4295-a011-dbe5395fc247.png)

FYI, the v7 DB files look fine after the second execution.  Also, we don't have any expansion units or M.2 cards in our system.

**Comment by 007revad** [comment] 2023-04-24 20:45
Thank you for all your testing.

I chose the easy way to restore the files by restoring them from their backups. I did realise that there was a risk of restoring an edited file if the .db file was edited before it was backed up. I'll work out how to make DSM download clean db files.

For the duplicating entries in the v6 db files I've noticed the script is also creating an extra file named rs2421rp+_host.db**r** with an "r" on the end. I haven't what is causing this yet.

I've found the cause of the duplicated entries in the v6 db files which has existed since v1.3.32 but nobody (including me) noticed until now. It will be an easy fix.

**Comment by 007revad** [comment] 2023-04-24 22:46
@Greg-ATG 
I've fixed the multiplying entries in the v6 db files issue. 
I've also fixed the v6 .db files being copied with a .dbr extension issue (which has existed since v1.1.10).

https://github.com/007revad/Synology_HDD_db/releases/tag/v2.2.43

**Comment by Greg-ATG** [comment] 2023-04-25 15:55
Everything seems to work great!  No redundant entries and the .dbr/.newr files don't reappear anymore.

It would be pretty cool if you can pull clean DB copies from Synology when using "--restore"!  If that doesn't work out, maybe it makes sense to create two types of backups:
1. <filename>.origbak
2. <filename>.lastbak

Where the "origbak" is created the first time the script runs (i.e. if "origbak" doesn't already exist) whereas any subsequent times the script runs and needs to make a change, it creates/overwrites "lastbak" so as not to overwrite the original backup.  I suppose this would require two different restore modes (restore vs restorelast).

Anyway, I appreciate all your work in getting these issues resolved!

**Comment by 007revad** [comment] 2023-04-26 02:25
> It would be pretty cool if you can pull clean DB copies from Synology when using "--restore"

Funny you should mention that. I added it to the develop branch, 3 hours before you commented :)

I just need to change one of the images in the readme to show the --restore option then I'll push it to the main branch and create a new release. Though I should probably edit the script to also delete any .dbr and .newr files.

**Comment by 007revad** [comment] 2023-04-26 05:11
I forgot to mention that v2.2.44 is now available. https://github.com/007revad/Synology_HDD_db/releases/tag/v2.2.44

- Added --restore info to --help
- Updated restore option to download the latest db files from Synology
- Now warns you if you try to run it in sh with "sh scriptname.sh"

**Comment by 007revad** [comment] 2023-04-27 08:15
If you've upgraded the memory with non-Synology memory you should include the `-r` option when running the script, to prevent [these annoying notifications](https://github.com/007revad/Synology_HDD_db/blob/main/images/ram_warning.png).

Try the `-f` option. So you'd want to use `-nfr`

The -f option should get rid of the firmware warnings until I can work out what 7.2 RC has changed since 7.2 beta.

**Comment by 007revad** [comment] 2023-04-27 22:55
Had you run my [Synology_enable_M2_volume](https://github.com/007revad/Synology_enable_M2_volume) or [Synology_enable_Deduplication](https://github.com/007revad/Synology_enable_Deduplication) scripts? They caused a couple of [minor issues](https://github.com/007revad/Synology_enable_M2_volume/blob/main/known_issues.md) in 7.2-6421**3** Beta - which Synology fixed in 7.2-64216 Beta.

Otherwise it sounds like a 7.2 RC1 bug. 

You can run `syno_hdd_db.sh --restore` to undo the changes made by syno_hdd_db then check if storage manager is back.

**Comment by 007revad** [comment] 2023-04-28 05:19
You don't need to run enable_dedupe as well. I was just wondering if you had used either enable_m2_volume OR enable_dedupe before storage manager went missing. 

- Both enable_m2_volume and enable_dedupe make the same change to the same file to make DSM think your drives are Synology drives.
- The only difference between those 2 scripts is that enable_dedupe also enables deduplication in synoinfo.conf and it checks the NAS has enough memory for deduplication (32GB minimum).

Are you still getting the firmware warning? And have you rebooted yet to see if the problem returns?

**Comment by 007revad** [comment] 2023-04-28 21:13
Someone with a DS918+ and 7.2 RC has also reported that lost access to Storage Manager, Snapshot Replication app, and most of the Hardware tab in control panel (fan speed, beep setting, etc). Also in Control Panel/Info Center "Model name" is listed as "Unknown Model" (instead of DS918+) and "Fan Speed Mode" is blank. It sounds like it may be because DSM doesn't know what the model is any more. 

This tells me that the issue affects not just business models or recent models. 

I'm going to check all the Synology forums to see if it is a known RC bug. If it's not then I'll switch off my DS1821+, pull my HDDs, install a spare drive then run my scripts, one at a time, to see if I can reproduce the issue.

**Comment by 007revad** [comment] 2023-04-29 02:11
> I repaired it by taking out all disks, adding a fresh one in empty slot one and installing DSM7.2RC1, re-inserting the old disks same slots while the system is running, and they popped up as "online assembly".

When you wrote "and installing DSM 7.2 RC1" did you mean you created a storage pool on that drive so it had a clean copy of DSM 7.2 RC1 on it's system partition, or that you were able to install the DSM 7.2 RC1 .pat file again?

**Comment by 007revad** [comment] 2023-04-30 01:09
I've noticed that the .db files in 7.2 RC include "smart_test_ignore" and "smart_attr_ignore" for all drives. In 7.2 beta and 7.1 it was only Synology drives that had those.

Synology drives have:
"smart_test_ignore": true,
"smart_attr_ignore": true

And in 7.2 RC 3rd party drives now have:
"smart_test_ignore": false,
"smart_attr_ignore": false

While manually adding your drives to a clean DS1832+ DSM 7.2 RC host db file (for you to test) I noticed that the firmware versions don't look correct.
- The SSD 860 EVO 4TB firmware version I'd expect to be like "RVT02B6Q" and not just "2B6Q".
- The WD firmware version I'd expect to be like "80.00A83" and not just "0A83".
- I'm not sure what to expect for the Ultrastar but maybe like "LDGNW240" and not just "W240".
- I'm surprised that the NVMe drives' firmware version is "ccc". Maybe ccc is returned when no firmware version is available.

Can you run the following commands and let me what they return:

`for d in /sys/block/sata*; do echo $(cat "$d/device/rev"); done`

`cat /sys/block/nvme0n1/device/firmware_rev`

`cat /sys/block/nvme1n1/device/firmware_rev`

If the last 2 commands return "No such file or directory" then run these commands:

`cat /sys/block/nvme0n1/device/rev`

`cat /sys/block/nvme1n1/device/rev`

**Comment by 007revad** [comment] 2023-05-05 02:56
@70m7E not responding

**Closed by 007revad** 2023-05-05 02:56 UTC
